---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgClGXCrPCZ1CdnJ+ao+fN5qheqDA5ZVLdEwsM/liNR/C9AZoEdXpKG6sYzhQHzJnP5KWcMBRZ+1I0hnFIht4g2i2xjKWXofuB3PjTgOgEbj0oo+lnTLyNMLiuWSJqHaEfv7zFBzdG0C2T+DivXddvFa90Rr0b43XhhKHc2seoCItrvxTbt3kTtTbDn99HFNJeDt2QNxWvaYJBR2Y6d84GRR3WKsspAadKiJZ02yCyC8WQ7igQpWoX4il00bTLMldYrlioVwxQ/DeKot01eFLGOGziuqpT3sXFRNh4gAFbO4SX3N7nYgvzfdsefQ2ncIndUoxaA6OM18rlo0fzMzJoaHVDW70ZFK1h/JPlHgRFJRRE7wDImMu5FluPEGdrOw29RrQrkdsi93TME5JkKL09Y/KzFHlsZSIB7nkZaqEqlH0yjdMdhlavYKxGe3XYl8UFxXDp1dFNpDdR0dMmXp8p1sqXvfFOBOlY+qSbc0RZGs1JT42VyKEPR5lxZTL7qrdoqmlqRGAngsaVfjPR48lM1DLN5ykatg0KdazrXyAJvOfMKaO+J/BmipJWhOHfZzqR+wxGZ3fMeeYzF9UUUo/3Cp/fxWAS/J/lr+VR+PxO1cix2ZNBDYmRBkYBiCmnzB8RPNij7y2xwKqsH9Rtrc844qU2jKXNZaYgWx5kGs6xSGEibNDxhxTNDm/CXSRvDUkwdMi2bwY+mxervjyycXBzdnNJsC2Shc8vJ8V92K5+IADNOTG36OyvHHHnkF0A==
    admin-user: AgAhkT/a0zJWz6yqdnehnw17FsHd95btR7vsHvL9YkC0H+gZ8fsHgwdsla21jNTPXno6s/AIDe5DSFTmgs0qKQGYIXpWf88cvxah3pZtuA6+YNztS0jAcW0tjjvyS1xOCGbWuss0IGlqvObsA7fnMaBdQ4ui9wYyW6da/UxA9EQw0mwAcR1SqImnxIQuuaSgdgJa/bnl3vqu2L/+Yo3JeKoqQpXvZwxV90QxNCZJOfwqASZUnXAmZBl2PH+puE9REpns4KNYYJtIMDo2PiItkq9Nxew34Xa2oztffvGCwQOBJjVlaa7CphTz+9dJl7bQzy67RteFnURSvqkXnzdUzBBQVRcXT2ziyL16uSDdbWrLBVjvXk4dG1VYdzuydVNQTuqvmDvlW+mODZYOerRmwS288l1QxQ1ziEyn26CYbvnN/33jr8zeU1a9Pj0ETgjqYuJFifSmCnwlKvJ61N5FEoS825JGYsLTF1Ccz52k5LfTWkDMsmW3W4s1Hb+Ff6kkOBw1G1xcPcc59l9noa7ey7mo7wHw3vi3afXCAYTZu8GwpImaXt2ajc63+qc5/vXVdok1XuzHhMxnYI8HRxjOoxn5QxLevky0YoGpKab8UmsZ1z9JLJjHKK9zntnWgzME3D0Zc3GuO4lKLr0eCFUb+eJDuLc9uEDdjFAFcBCfdzZs7zK83Vwgr3HyOa8azXq2nFC9BXoLeA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: grafana-admin
      namespace: monitoring
    type: Opaque
