---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBVrS+nQMXZhmy+V471EMQpdnUy9c4xE/7B4bfPQCqJNoZuYt8lrUGwEq6J7fdr9xx5OgcEN+qljBhT8J6aiUAyEYZkECUKmrhFeAxNKlFHJISuFwUMKIckbPOKyUpjS4YREu2sucyZuraQIcVVPwrwPMN4usmjqq7BFTYa6iUNn3o263R4odU0zLIhNqjU5/S0x1I7rTp8uEhhDmjbIT1afsA3ZrXN2UNe8EsYYOF2ogyejNl4YcAAWqvF9Nk96N15Dj0HudnUz3udLB31h/BFK+v/j8etO8OLhIZ9qfwZDi2WbUi7dNhSvOkw2iX9MiuQK4OaS17Gmk60inkkORRO5n1dv1jObzHA+7SZt1i1cHqk7za/6Ks0ddT8Vl6ZxoFVv83fVyMr591ptvoURldeZI9rEX/5KG7gm9q5MzAvojZYVmuWaOAQDxPBY1vu7CRdyTP4Vsilov+jdzi2ORr1VsXysogrI9o7DIHi7upkt4bDjd+KzlahYQaZGwMKOkw7SAtoNOcvK/+JY0aq5XlN1yIzecZhrQgp6aE+9FT1JuCZyR+ZCIP4eTOAdmtB0v/gAcR3llf9RcovXcqJf48zwifUpWmbREBuoEO3jP0+tiufUDvSLiwP9xjdBV64h93jDiRf+epCJvst6v26xBbPykQG5qHX2i5r9sllO4G4H9H02geZnXHZiZBZh8+cmQ1WIZikk09ioxcH7FG11zhBde5Ruwlu3D+UnJ6qe63yjTD09iS1o+ZAZ1n0S2RRwOccBFr43Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
