---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secrets
  namespace: ai
spec:
  encryptedData:
    SEARXNG_SECRET: AgAawyat7TyBzDk4BCziZuNcZHyA7d3H5QcBb9ncR2wsv3oyPNO0NvgXsNDtDk3RXVWo6BHMy76GoSfS5BmEflF0xBGlHs4lqaMfj0/ktsPpNAHZhvO8YA9fnKLwOc4GUE64MtJLRFCaJE3Vk32RAEAGHobKM4QYMtMP+cedD0l2dlAbsHpUPBZBoTLoCGyqs71Ww3EgyPTiSlnvAdIFtYk/7UmZTtyj697byesL8EYGpzk1kVATiab4ulRujXlciByZF0dWPwmIwCbKqvoh9YwjFLnfzoGaZ1JNcVdwxh0NIYCPdosf/9xLEf2AwiWftPapzY7bfXlZr6z0oOrtTIq+aYpFmNSbk9DXgKzcxZQR2mQSB10MOxfS/E0Ljmn1tmU8BeUZHvIb0ME0xQzzvYIPjMKX7LV4zZxd38KO+ZovBtU3+i//ic0QwoffaFus8Jo8zhWWVOd0rQ8pIYWLynXfb7TorMN+Rr4okQFP0OTrhDpw+vXj88EtFPpqnb+SSvbxymVW2RP8Bl9Z2kq0PW1CmhjFHGHXAr4CY7eL4ThXVIzehjRMkJOrKLEVQugxStoLLTZSGa1Os7wdsu+em/t+uTEMa3xtSQEgPsfNl7t7SxoGG3f40QuPUtpCm9Z+88b6Wvs+N3cB2wEvmnh39E8/o0/v0oxcOSJk5uB2wX1MnFvgv2MXn0obRcO9/JtK1p+0ICrQqqLm3uuEcrPx9NqUG4ZZmUsW+yFJqWFs8ahbjcNy6xIlV1LnpnNBAAo0Cif+oqy0h8X0kGe61DD+Lov7
  template:
    metadata:
      name: searxng-secrets
      namespace: ai
    type: Opaque
