apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-defaults
  namespace: development
  labels:
    app.kubernetes.io/name: code-server
data:
  settings.json: |
    {
      "editor.fontSize": 15,
      "editor.minimap.enabled": false,
      "editor.renderWhitespace": "selection",
      "files.autoSave": "afterDelay",
      "files.autoSaveDelay": 1000,
      "git.autofetch": true,
      "security.workspace.trust.enabled": true,
      "telemetry.telemetryLevel": "off",
      "terminal.integrated.fontSize": 14,
      "window.commandCenter": true,
      "workbench.colorTheme": "Default Dark Modern",
      "workbench.startupEditor": "none"
    }
  keybindings.json: |
    [
      {
        "key": "cmd+w",
        "command": "workbench.action.closeActiveEditor"
      },
      {
        "key": "cmd+shift+t",
        "command": "workbench.action.terminal.toggleTerminal"
      }
    ]
