---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql
  namespace: identity
spec:
  encryptedData:
    password: AgBbN268qbQugZxlyDXetE+Y8OWFG9OyAyTqGX0jnNlw7rRlgWEXJ4YUOQQfQKqURaJ0duRpmnawC3O0A/Hwme/kW/qebjA4/m1TPmlKiWuHgsX3AJ2vsx0M78ztG0FTOUnbcbwp2lOF3tcvNSUY7zXmIE3qtvqLps0mViCu9eGbAADEPytOss1EAS9kkQH0BNFGOQFu2MuGTLvAb7kHQK1bh3K4lQWb/7kUSW61GWlhyapISE9kWr4VHwb+zos0mA0MYe6/3Xp2rarhsoxIGVDEURNzJ0cvwSsiazwBGCZHCKb67jAqHs1bD6fsykRlCPZiQ2JRpOMGnaUhxWSSbNvMY6WXmgRl/p3D2OXw2BiU+S+775Tzhtds659l1VE5STfaXx/BoxVKU6FW468g6hz7KZ7vv8JkdV7V6D0qe02X9ayiOTjXZpAr+uRH6Fsk8i58nQE1y8VZfVJ8iq1kssOMJvrwnw3Y7D9N5FKXYGr68BfNjQmbp3bI67Vrfo/bI0quZdQqNTvECk8KPvo/G8xXo/jeQTJVPCO5WIfE8Wfe+x4QCSjIlFq4tXYPCS2vf/DRE4xevhVd+79YQaD69w0N086YwYma7tT2evTUdQ6Hx9UjMRpKZiFaqplFvn91w1hslBCjM2CP3f2d8Hx7x82A0dmwIqoYEyzqGCTifaAIatbhpZIdHw77AiyFD0eUdsestvcVg0uxAMYBB6mgVZeJMKtRwj9+kpirkopD+VnuJS13NfhfwmuXnFc6Ylp+/9c=
    postgres-password: AgBwk/etSdO0+SwCcJQvN6ZJ3DPwkETYVnEdmbm6HQt7TxubVw6W4FxBKhY1C+B03ymPW6OtzTBdtFRMYrYYHMtIIgmYoVYFrPDvhDGh7F7pUFfLbWv3RPMH4EcFkRivE9RiEw2+FGWHtSQSF1Edk0rMHESr6zgQTEzsMcdqC4M8KM3ta0QT0EFpcezeyodHNmPjqnnlmnoVnwI+IikhQdfA5L1HWrb2VsbiDoVG1OTVGny97L2ekFQLjOm9VR++5wfZ97sgnxolCUHV0sT2UYo/u3J73sBm/Ppj/iuUx7/OQksL8tritoreL9kThSh/rOUVlfFunLzFVWgctJbc5QOaL9kTSXb5VYvPRcxqL8425+9rfcL9rCOv5mkiK4Vo9iQSP6Bq45FoJGtX5LS2aTPbb5JC9UyKMLGDvBBuKUtrjeUY7QIOrc2QfcQLlHMEpNAeqrCbZ2pJjEWVyLdTtcnpPlV4IjpoymqI8pN7aPV22lg+jkDkJ4hkfqPpTyyI3ea6R2s849BEd46/F6U/fplS4xk/Kcct43VUtS91/jjXZi93PiHX3YPEaHUJL+9ApSTHTIHXZ0daYUK9+uLkRE/pO8sdeXAJMt0MAOsS8GCBDdDrsxixgO2ji/HfyBwzb7nbXzbr/e5nx5n6PbQxL7z2T2QZFwuqUHtFGGp58liL90CpbGQCouYzbvbwHKR0l5gz/2aupPUTUxnezo7yzdANp+bzbb2liiVZZGmhKPgu3DXT0kEueGuNEbBirFUIzeo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: authentik-postgresql
      namespace: identity
    type: Opaque
