apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: studentlens-uploads
  namespace: studentlens
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replica
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: studentlens-redis-data
  namespace: studentlens
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replica
  resources:
    requests:
      storage: 2Gi
