apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-watchdog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SirNotEthan/Homelab.git
    targetRevision: main
    path: kubernetes/platform/cluster-watchdog
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-watchdog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
