apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SirNotEthan/Homelab.git
    targetRevision: main
    path: kubernetes/platform/identity/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
