apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SirNotEthan/Homelab.git
    targetRevision: main
    path: kubernetes/applications/stirling-pdf
  destination:
    server: https://kubernetes.default.svc
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
