apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: ai
data:
  settings.yml: |
    use_default_settings: true

    general:
      debug: false
      instance_name: "Homelab Search"

    search:
      safe_search: 0
      autocomplete: ""

    server:
      base_url: https://search.apps.lab.sirnotethan.uk/
      bind_address: "0.0.0.0"
      port: 8080
      limiter: false
      public_instance: false
      image_proxy: true

    ui:
      default_theme: simple
      query_in_title: false
