---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: studentlens-postgres
  namespace: studentlens
spec:
  encryptedData:
    DATABASE_URL: AgBaVL5wR8j4CTmL6Y+dPZmGT3NJ56r5e7y0BZ07fWIiYX4upC8PVXk/PsA4zgX2vw33Xa850aExAbpcva38ngzWzIlFhi0dLWf8FrUJUWKUK5n7p1sg9PbJmxYE1Hhp8JuAVTK5ftqbE/v4JebHXHTI6VIj1Igd/wzrC6iuBFXAIzTbWcM1MOBlXOXEgjNXRnMas7lbErlRs4BldiFfoZTPMd50iiEwaHdNJ1SW2D21NpiJy1RuYA02odiZ4LXMPgR3rMxHDZPmo9heptASOkUvWmtFlfXXnF6mvz0/su8/IoH92Qw5/N932/WwN2ftJUuKT1h3vG2MPzsHhdmMYMuf7cNX+c2vJzULYcXA+cZ3jv6Kv/KV82IJv7rS2d7jLN1IWuwuAi6ALT7bIMgXZkPucTEtHM8elbrzvTfy6tLAO/+hy7ThYgQADcEvQGjChpOluo2kbupc8LeT/1ragtnMlfxFH5NPA4Ibli0swtJH3qATpEd+j3toU2DLYDI8rvXESfjFfv+b+nXVrudqKO6hFAkBZsqu2d4q5xXJkInBU0sdphj5jcExzW5eJA84ok+hrp9h+JQJM98Eg7nDbHrPjATGWZq0wnoLz0tIgb8DHMd5c/xzM1QCg12ABi0UVTdoLF7vp8ZrQ+hafdji6Ja3fIDazU9RkRcNUagMvWZnM/S5URtaYMbcXGm1BVbdvk0=
    POSTGRES_PASSWORD: AgB+5YF7fcrOtflot9+UV6RNmcu0QJ+guNU+O1QlUTE6UHXsra+dgEONroFHHDQ8sgN292kzWrH0HW3Ppd+6rR3g0nTpVuzBecZKQ1Ah05dfIBcU1A6E1MfmbqKWF6Eu2THIOwaJS5SIz2D12p4qN2TjCVyhnPPPSQWm9tuPzWT0xTgAOXXGdZWQMuwSrqZeqOkYc/VUFxQCkEBf+RF8YLUddviDIpSiKR+kvJD6YY8SAb/L7/xrXi/fCzZYKEBoo74BtY3vq5KacacHg+PJoqKGDZQCOP7Lydqqmw5jyvi/1EtQ5fA2PoGlDb43zTxaXyLUBvqi3q0pW41/R3BrTjiz7UBm+RlRrcLn1BGvuL0rRxrNlkPLdDz65ip3r0wWsWB2F6MwE3eGXO+/AlC7jmWSS9QLLM3BYVtA1P45tkoyaSyg/moUoP2y91r2pLWwRtzOJ9zDi7BG2VIy3nCKGW+yFsaAcJpWE76maPhLndKymL6WrJ03c/5w6DEKInKVep5bpJvqV7CaA3MjiCpnDgtsyPO8d1HcWldKzChDP1G6fPGRiSR/0Jk32/+SEb812uWDg7P5CAvVrDvjJpZFgYGFUoS36GQ9u+GXtHT+0s1o2vIy3a4GQKVRK/CmHAUTQQDRmNnAntV+P634SQUqmDZnT8plzt6qYEAzA8XbYbj1g/C5V9AUHW9PIH41IUCH1vQ=
  template:
    metadata:
      name: studentlens-postgres
      namespace: studentlens
