---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBn2NzeUqdMLaexYbL2PP8iGH5lP1m2eMsiz8YFMJiqdPhUHiyam6t+YTJwACMrVCUOx/RTvCtiGeCs+LHwpzgEL2fnTWbRmlhe8wFfGyWZcVvPBjg8+X+euKDwTXtGUEl4683XOknxBiTy/R7Gt58GRaPH5XpBryn0JSeBVKoqYY4KYI7nIqEDhRDzk9/W20ZZTs6CWAseroZr5HmHtzWgYmZBO+NqoI6IN3wdgshs5UZCK7v/wXDuLM7riHVBWT15wAA5vJc7vWqGmjqz9YKclz17pI7RPMNMYqgX4SYXeJ2UDT458ywRW6q6OrN8vi5NxmeqShU/E4GSiPmuchlste6eyD2dtv0l9tdo0FayzHK+ddwVCPlyhEtWT5ZRCgMpouOgDDxyjzTJ9l5nBHaMZ/M7XQZsyIDg5hDW+rMi78+0vFWxMf7KId9+tS1RrYVfNcJwa++TUV/LrAb0Y29QSPv5OJA8M9N/5SyyAymaQ+FwH8s/yxq2Y/GZsf5zJm3p7GTynED+Vk16TTlaaqiiys75ESFs6xJwHI5Iss/M01AE0/Td6h4LGpiz90bSgK8VmDkEeoCQTjE4WMy6TI5vt7jQSgilJqR/XXAZpJ6kybx0O1qn6Fe1lZRMxnKxz2VmenPuIuvrUQClUGuMIwbhN+ZVKKe2WVB0cJDORtTAm3FEXhZVUSfD6t9zcxLNy31M6ky+KuHr3kyMdRrMuA41p7QJexJgXPb08S9hU4Hgu94xz07N8SjxWqnFJPMsTP5Rn/xvpbpf98qIJfimxgRv28JhUo2AobZzqoBgHy2J7tEUO8fFWh302FeAtPX6OM+6pwVyzQBhLVtR2c2AeWWnUYCN33lSAiC/JvozuGQ6wgdDFUPhOfR5Cu/mrz5MsOZTB1QytYl0qUZnaqmxUWCKB3cDRE/VNrPvxPuuOCoWMh/ZpIHVR8xX
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel
