apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  bookmarks.yaml: |
    - Homelab:
        - GitHub:
            - abbr: GH
              href: https://github.com/SirNotEthan/Homelab
  docker.yaml: ""
  kubernetes.yaml: |
    mode: disabled
  services.yaml: |
    - Infrastructure:
        - Traefik:
            href: https://apps.lab.sirnotethan.uk
            description: Ingress controller
        - Longhorn:
            href: https://longhorn.apps.lab.sirnotethan.uk
            description: Persistent storage
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
    headerStyle: boxed
  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
