apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replica
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replica
  resources:
    requests:
      storage: 5Gi
