apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pterodactyl-mariadb-data
  namespace: pterodactyl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replica
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pterodactyl-panel-var
  namespace: pterodactyl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replica
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pterodactyl-panel-storage
  namespace: pterodactyl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replica
  resources:
    requests:
      storage: 5Gi
