apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-access.yaml
  - applications/cert-manager-config.yaml
  - applications/homepage.yaml
  - applications/identity-authentik.yaml
  - applications/logging-alloy.yaml
  - applications/logging-loki.yaml
  - applications/monitoring.yaml
  - applications/sealed-secrets.yaml
