---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: code-server-auth
  namespace: development
spec:
  encryptedData:
    PASSWORD: AgBybj96D78K0k0RxlBvX2lvMzFFwtFjbZOn1k9jbHVGX1+YxMmZMOQxsS4OHrP4lRkpU0v9cGyaVvFYea7E8WuXm5/JXKWVuF0WPUi7D9NGRzlzYFXUKfSWENy6VipUHON791mvd3ArFbxcyEiSRvMZzQRUoNXVuQoFK71x+tYVE96V2/UDjdVm8zbTwKAguMHVyHY9Hyw3KtmCtHewWu13EQW4Su2M1oUUbbrDCiChoRiViPkP+5rvwFRgHfDmW7uY/YDX+Zoj8rTSP/qfCqwtgPYfDbgKk+Cv2gU7BbLh08V3qJ+EnMmhqnl3qmt5xJPb3qPuLxVD7I9dTuPW6U+6hCE5Q5sAV+zyZFtUp49LB2j987iAGbHqfMomszvUn+gsGDA1S8bgXsbZvbUMHZikxFI+GJ2OMMMm92WoAR5GGN39YvBap38jJj4h1S0iRl0SrdAxxRXYzci2yRJ6NBX+Sv7x+Ji/Bi2Omhobg4YrDFcWl5E6hABo0IMDLtGHHp+Pz6WIkMyXWwIg7/9nytcpLqpjp4JnvDsLvq2MrvTzdgvV0S2+AL+DHWiaR9j1w+GuMvxKxIhSprwZI8QMwctXGYwyMFe9Nqyoe6qappX/Tn3aQ+FeME/eIXj7+PkecUF4LTvLD4+uMqZV8TgVpUX7ABzmybUPoxQ6pFFoKpHkdP9OQ6k65NTl7KCQIG7Tk0RdQs/FL9u4RoDHlJUhVy+KAIJYXbzBywbi2Z2IP2VNAA==
  template:
    metadata:
      name: code-server-auth
      namespace: development
    type: Opaque
